### ISSUE TITLE
Conditional rendering for weather

### ISSUE THREAD

**Issue by OscarJonasson** [kirsijo/countries_app#1]
Clicking on South Georgia > See More breaks the site. 

openweather returns 404.

https://api.openweathermap.org/data/2.5/weather?q=King%20Edward%20Point&appid=XXXXXXXXXXXXXXXXXX&units=metric
404 (Not Found)

Possible solution:
- catch error in fetch part and use a boolean state.
- if the error is true, conditional rendering that only presents "unable to load weather".

**Comment by kirsijo** [comment]
Thanks Oscar! This should now be fixed.
